# include:
#   - board: seeeduino_xiao_ble
#     shield: totem_left
#   - board: seeeduino_xiao_ble
#     shield: totem_right
#   - board: seeeduino_xiao_ble
#     shield: totem_dongle prospector_adapter
#     snippet: studio-rpc-usb-uart
#     cmake-args: -DCONFIG_ZMK_STUDIO=y
#   - board: seeeduino_xiao_ble
#     shield: settings_reset

include:
  - board: seeeduino_xiao_ble
    shield: totem_left
  - board: seeeduino_xiao_ble
    shield: totem_right
  - board: nice_nano_v2
    shield: totem_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: settings_reset